version: '3.9'

services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: postgis
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- ./postgis/init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # <-- chemin vers ton script d'initialisation SQL
    networks:
      - gis-net
    ports:
      - "5433:5432"

  geoserver:
    image: docker.osgeo.org/geoserver:2.28.0
    container_name: geoserver
    restart: unless-stopped
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=gates123
    volumes:
      - gsdata:/opt/geoserver_data
    networks:
      - gis-net
    ports:
      - "8080:8080"
    depends_on:
      - postgis

volumes:
  pgdata:
  gsdata:

networks:
  gis-net:
    driver: bridge
